# Generated by Django 3.0.8 on 2020-08-07 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 20, 52, 0, 45472)),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Replies',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Seen_By',
            field=models.CharField(default='Unseen', max_length=100),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Seen_Date',
            field=models.CharField(default='Unseen', max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Seen_Status',
            field=models.CharField(default='Unseen', max_length=50),
        ),
    ]
