# Generated by Django 3.0.8 on 2020-08-12 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200812_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='New_Complain',
            new_name='New_Notifications',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='New_Re_Replies',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='New_Replies',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='New_User',
        ),
        migrations.AlterField(
            model_name='complain',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 20, 56, 48, 299539)),
        ),
        migrations.AlterField(
            model_name='re_replies',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 20, 56, 48, 300531)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 20, 56, 48, 300531)),
        ),
    ]
