# Generated by Django 3.0.8 on 2020-08-12 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200812_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 21, 58, 28, 316379)),
        ),
        migrations.AlterField(
            model_name='re_replies',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 21, 58, 28, 317370)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 21, 58, 28, 317370)),
        ),
    ]
