# Generated by Django 3.0.8 on 2020-08-12 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20200812_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 22, 20, 47, 889299)),
        ),
        migrations.AlterField(
            model_name='re_replies',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 22, 20, 47, 891270)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 22, 20, 47, 890301)),
        ),
    ]
