# Generated by Django 3.0.8 on 2020-08-14 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20200812_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 13, 0, 55, 985288)),
        ),
        migrations.AlterField(
            model_name='re_replies',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 13, 0, 55, 986285)),
        ),
        migrations.AlterField(
            model_name='replies',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 13, 0, 55, 986285)),
        ),
    ]
